#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    vimcompatible = true
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true

    
    bootstrap_before = "myspacevim#before"
    guifont = "Consolas:h11"
    filemanager = "nerdtree"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]  # 中文文档
  repo =  'yianwillis/vimcdoc'
  merged = false
[[custom_plugins]]  # 括号 [command] (y/c/d)s
  repo =  'tpope/vim-surround'               
  merged = false
[[custom_plugins]]  # 文件树
  repo =  'preservim/nerdtree'               
  merged = false
[[custom_plugins]]  # 快速移动光标 [motion]
  repo =  'easymotion/vim-easymotion'        
  merged = false
[[custom_plugins]]  # 代码注释 [command] gc
  repo =  'tpope/vim-commentary'             
  merged = false
[[custom_plugins]]  # 交换文本 [command] cx
  repo =  'tommcdo/vim-exchange'             
  merged = false
[[custom_plugins]]  # 复制高亮
  repo =  'machakann/vim-highlightedyank'    
  merged = false
[[custom_plugins]]  # 替换 [command] gr
  repo =  'vim-scripts/ReplaceWithRegister'  
  merged = false
[[custom_plugins]]  # 方法参数 [motion] (i/a)a
  repo =  'vim-scripts/argtextobj.vim'       
  merged = false
[[custom_plugins]]  # easymotion中文扩展
  repo =  'ZSaberLv0/vim-easymotion-chs'     
  merged = false
[[custom_plugins]]  # 多光标
  repo =  'terryma/vim-multiple-cursors'
  merged = false
[[custom_plugins]]  # tpope repeat
  repo =  'tpope/vim-repeat'
  merged = false
